name: Build

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build bot
        working-directory: ./bot
        run: |
          npm install --legacy-peer-deps
          npm run build:silent
