name: Deploy api to server

on:
  push:
    branches: [master]
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieving modified files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script_stop: true
          script: |
            cd /Work/RusAnonymBot
            git fetch --all
            git checkout master
            git reset --hard origin/master
            git pull
      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script_stop: true
          script: |
            cd /Work/RusAnonymBot/api
            rm -rf ./node_modules/
            rm -rf ./dist/
            npm install --legacy-peer-deps
            npm run build
      - name: Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script_stop: true
          script: |
            cd /Work/RusAnonymBot/api
            pm2 stop ./dist/main.js > /dev/null
            pm2 start ./dist/main.js --name="RusAnonymBot [API]" > /dev/null

      - name: Final
        run: echo "Succesfully deployed"
